# docker-compose.yml
version: '3.8'

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    # установить рабочую папку внутри контейнера
    working_dir: /app
    volumes:
      # монтируем только код приложения
      - ./src/PriceSpy:/app
      # монтируем шаблоны, если они лежат вне src (или уберите, если перенесли в src/PriceSpy/templates)
      - ./templates:/app/templates
      # монтируем локальную БД
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      SECRET_KEY: change-me
      REDIS_URL: redis://redis:6379
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 8000
        --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - ./src/PriceSpy:/app
    environment:
      REDIS_URL: redis://redis:6379
    command: >
      python worker.py
