# docker-compose.yml

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      SECRET_KEY: change-me
      REDIS_URL: redis://redis:6379
    command: >
      uvicorn main:app
        --host 0.0.0.0
        --port 8000
        --reload

  worker:
    build: .
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379
    command: >
      python worker.py
